name: Metrics
on:
  schedule:
    - cron: "0 0 */5 * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - name: Last.fm  - Recently listed
          uses: frieren-mage/metrics@master
          with:
            filename: metrics.plugin.lastfm.svg
            token: NOT_NEEDED
            base: ""
            plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
            plugin_music: yes
            plugin_music_mode: recent
            plugin_music_provider: lastfm
            plugin_music_user: xxspell
